apiVersion: v1
kind: ConfigMap
metadata:
  name: c-service
  namespace: practice-helm
data:
  application.yml: |-
    server:
      servlet:
        context-path: /c-path
    spring:
      application:
        name: c-service
      config:
        import: kubernetes
    management:
      endpoint:
        health:
          enabled: true
        info:
          enabled: true
        restart:
          enabled: true
