apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
spec:
  replicas: {{ .Values.replications.desire }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image.registry" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
            - containerPort: {{ .Values.service.server.port }}
