apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
    - port: {{ .Values.service.server.port }}
      protocol: TCP
      targetPort: {{ .Values.service.server.port }}
  selector:
    app: {{ .Chart.Name }}