image:
  repository: trucnguyen301197
  prefix: helm
service:
  name: c-service
  namespace: practice-helm
  server:
    port: 8082
    servlet:
      contextPath: /c-path
  config:
    import: kubernetes
  management:
    endpoint:
      health:
        enabled: true
      info:
        enabled: true
      restart:
        enabled: true

replications:
  desire: 1
